# Generated by Django 5.1.1 on 2024-09-26 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_cv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CV',
        ),
    ]
